import L from "leaflet";
import "leaflet/dist/leaflet.css";
import markerIcon2x from "leaflet/dist/images/marker-icon-2x.png";
import markerIcon from "leaflet/dist/images/marker-icon.png";
import markerShadow from "leaflet/dist/images/marker-shadow.png";
import { MapContainer, Marker, Popup, TileLayer } from "react-leaflet";
import type { MapLocation } from "../../types/map";
import { pixelToLatLng } from "./mapCoordinateUtils";

const TILE_SIZE = 256;
const MIN_ZOOM = 0;
const MAX_ZOOM = 6;
const MAP_IMAGE_WIDTH = 4677;
const MAP_IMAGE_HEIGHT = 6622;
const MAP_BACKGROUND_COLOR = "#D2B790";
const TILE_URL = "/tiles/{z}/{x}_{y}.webp";

delete (L.Icon.Default.prototype as unknown as { _getIconUrl?: unknown })._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: markerIcon2x,
  iconUrl: markerIcon,
  shadowUrl: markerShadow,
});

interface MapViewProps {
  locations?: MapLocation[];
  selectedLocationId?: string | null;
}

type MapLocationWithPixelCoordinates = MapLocation & {
  x: number;
  y: number;
};

function hasPixelCoordinates(location: MapLocation): location is MapLocationWithPixelCoordinates {
  return Number.isFinite(location.x) && Number.isFinite(location.y);
}

function MapView({ locations = [], selectedLocationId = null }: MapViewProps) {
  // Keep these values aligned with public/tiles/metadata.json generated by scripts/generate-tiles.js.
  const southWest = pixelToLatLng(0, MAP_IMAGE_HEIGHT, MAX_ZOOM);
  const northEast = pixelToLatLng(MAP_IMAGE_WIDTH, 0, MAX_ZOOM);

  const mapBounds = L.latLngBounds(southWest, northEast);
  const validLocations = locations.filter(hasPixelCoordinates);

  return (
    <MapContainer
      crs={L.CRS.Simple}
      bounds={mapBounds}
      boundsOptions={{ padding: [24, 24] }}
      maxBounds={mapBounds}
      maxBoundsViscosity={1}
      minZoom={MIN_ZOOM}
      maxZoom={MAX_ZOOM}
      zoomControl={true}
      attributionControl={false}
      style={{
        height: "100vh",
        width: "100%",
        backgroundColor: MAP_BACKGROUND_COLOR,
      }}
    >
      <TileLayer
        url={TILE_URL}
        tileSize={TILE_SIZE}
        minZoom={MIN_ZOOM}
        maxZoom={MAX_ZOOM}
        minNativeZoom={MIN_ZOOM}
        maxNativeZoom={MAX_ZOOM}
        bounds={mapBounds}
        noWrap={true}
      />

      {validLocations.map((location) => {
        const markerTitle = location.name ?? location.city;
        const markerCategory = location.category ?? "landmark";

        return (
          <Marker
            key={location.id}
            position={pixelToLatLng(location.x, location.y, MAX_ZOOM)}
          >
            <Popup>
              <strong>{markerTitle}</strong>
              <br />
              Categoria: {markerCategory}
              {location.description ? (
                <>
                  <br />
                  {location.description}
                </>
              ) : null}
              {selectedLocationId === location.id ? (
                <>
                  <br />
                  <em>Local selecionado</em>
                </>
              ) : null}
            </Popup>
          </Marker>
        );
      })}
    </MapContainer>
  );
}

export default MapView;